version: "1"
services:
    name: agent-test
    repo: https://github.com/MohamedBasueny/realtime-playground.git

    # Path containing the Dockerfile
    rootDir: agent

    # Runtime: Docker-based
    runtime: docker

    # Plan for the service
    plan: starter

    # Environment variables group in Render dashboard
    envVars:
      - fromGroup: agent-example-env

    # Region (validate the name in Render's docs)
    region: oregon

    # Maximum allowed shutdown delay
    maxShutdownDelaySeconds: 300

    # Scaling configuration
    scaling:
      minInstances: 1
      maxInstances: 4
      targetCPUPercent: 60
      targetMemoryPercent: 60
